CAP-26 Implements CRUD company
jobfaironline/jobfair-backend pull request #17
Opened 2022-01-12 08:51 UTC by CaoSon1909

2022-01-12 11:09 UTC, TienTruong2000 requested changes

2022-01-12 11:09 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/controllers/payload/CreateCompanyResponse.java
> +
Why do we need this class, we already have GenericMessageResponseEntity.

2022-01-12 11:09 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/config/SecurityConfig.java
>                  .anyRequest().authenticated().and()
Why company endpoint get permit all

2022-01-12 11:09 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/controllers/company/CompanyController.java
> +
Controller should never have Repository, please use Service

2022-01-12 11:09 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/controllers/company/CompanyController.java
> +        CompanyDTO dto = new CompanyDTO();
Please check Bảo's code for builder pattern

2022-01-12 13:07 UTC, CaoSon1909 commented on src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyService.java
> +    List<CompanyEntity> getAllCompanies();
findAll() trả về List<CompanyEntity> mà

2022-01-13 04:16 UTC, TienTruong2000 approved these changes
LGTM

2022-01-13 04:16 UTC, merged