[CAP-108] [BE] - Implement attendant create application
jobfaironline/jobfair-backend pull request #73
Opened 2022-02-19 10:51 UTC by CaoSon1909

- 19/02/2022: work in progress

2022-02-20 10:36 UTC, TienTruong2000 requested changes
Change please

2022-02-20 10:36 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/controllers/payload/requests/account/cv/CreateApplicationRequest.java
> +    private String summary;
No constraint????

2022-02-20 10:36 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/services/impl/attendant/cv/ApplicationServiceImpl.java
> +@Service
Where is @Transactional

2022-02-20 10:36 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/controllers/attendant/cv/ApplicationController.java
> +        catch (NoSuchElementException | IllegalArgumentException ex) {
Remove catch please

2022-02-20 10:36 UTC, TienTruong2000 commented on src/main/java/org/capstone/job_fair/services/impl/attendant/cv/ApplicationServiceImpl.java
> +        resultDTO.setStatus(entity.getStatus());
comment clearer please

2022-02-24 14:22 UTC, BuiMinhKhoi approved these changes

2022-02-24 14:23 UTC, BuiMinhKhoi approved these changes

2022-02-24 14:23 UTC, BuiMinhKhoi approved these changes

2022-02-24 14:25 UTC, TienTruong2000 approved these changes
LGTM

2022-02-24 14:25 UTC, merged